### ISSUE TITLE
Pypi maintainers

### ISSUE THREAD

**Issue by liamcurry** [liamcurry/py3kwarn#6]
@dustinmm80 and @myint, I added you both as maintainers in the pypi repository. Feel free to update the repo as you please. Good work!

**Comment by myint** [comment]
I noticed someone uploaded a version with a [strange](https://pypi.python.org/pypi/py3kwarn/.-0.2.0-) version identifier. So I reuploaded with the [correct](https://pypi.python.org/pypi/py3kwarn/0.2.0) version identifier.
