### ISSUE TITLE
Should we modify lib2to3?

### ISSUE THREAD

**Issue by liamcurry** [liamcurry/py3kwarn#7]
Since we are already bundling `lib2to3` with this package, do you think we should modify it, or leave it as is? There's a lot of code in there that could use some cleaning up. Also, if we're looking to increase performance then we'll probably have to do this anyway.

**Comment by ghost** [comment]
I'd say since we're vendorizing it, we might as well improve it. If it was being continually released, we would have to worry about compatibility, but since this lib isn't changing on 2.x I'd say we can fix it up.

**Comment by myint** [comment]
If necessary, then sure. Though we should keep in mind that things like [`python-modernize`](https://github.com/myint/python-modernize) manage to do everything they need with the default `lib2to3` (without vendorizing/modifying). And it even works on Python 2.6, 2.7, 3.2, and 3.3. (See the `unwanted_fixes` [code](https://github.com/myint/python-modernize/blob/master/libmodernize/main.py) for example.)

**Comment by liamcurry** [comment]
@myint True, but the goals of these projects seems to be different. `python-modernize` and `lib2to3` have a large emphasis on automatic refactoring of existing code bases, whereas `py3kwarn` is basically just a syntax checker used to help developers write forward-compatible code.

**Comment by myint** [comment]
Right. I only mention `python-modernize` so you guys know that you can get pretty far (in terms of both functionality and Python compatibility) with the default `lib2to3`.
